version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  steam_collector:
    build:
      context: .                     
      dockerfile: app/Dockerfile     
    volumes:
      - ./scripts:/app/scripts
    command: python scripts/dump.py

volumes:
  mongo_data:
